### ISSUE TITLE
cssnext already include autoprefixer and cssnano

### ISSUE THREAD

**Issue by MoOx** [eggsdesign/egg-incubator#1]
- autoprefixer is already in cssnext, you can pass directly the `browsers` option http://cssnext.io/usage-/#browsers
- cssnano is included as `compress` option http://cssnext.io/usage/#compress

You should update your boilerplate according to these changes.

Btw, I am curious to see where did you see how to include cssnext? Too many people are doing the same mistake and I am tired to notify people about this, so I would like to know where, so I can add a notice or something... :)

**Comment by MoOx** [comment]
Btw, if that just what you need, cssnext have it's own interface & plugins (gulp/grunt-cssnext, etc) http://cssnext.io/setup/

**Comment by Quball** [comment]
Thanks for you reply MoOx, we followed the setup described at http://cssnext.io/setup/#usage and used it as a postcss plugin.

**Comment by MoOx** [comment]
So I guess current cssnext documentation is not clear enough about the inclusion of autoprefixer & cssnano?

**Comment by eplehans** [comment]
@MoOx  Yes, it seems a bit unclear at the moment.

**Comment by MoOx** [comment]
Ok, I will try to find a way to make this clear.

**Comment by eplehans** [comment]
@MoOx Great! I'm guessing it will help a lot of people out when experimenting and dipping their toes into the postcss and nextcss world.
